### ISSUE TITLE
Jan ToDo list for Kieryn

### ISSUE THREAD

**Issue by kiery** [sfyimby/sfyimby#25]
- [ ] Lektor template for comics
- [ ] Category template (for lack of a better word) to embed in media page
- [ ] Category pages: Podcast, Comics, Video
- [ ] Get ads on front page (template needs changing, then css)
- [ ] Setup nav
